modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Mrbysco/UHC-Mod/issues"
license="MIT"

[[mods]]
modId="ultrahardcoremod"
version="${file.jarVersion}"
displayName="Ultra Hard Coremod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ultra-hard-coremod"
authors="Mrbysco, ShyNieke"
credits="A UHC mod highly inspired by Gerrybrano's UHC Blox"
logoFile="logo.png"
description='''
A UHC mod made for Modded Minecraft
'''
[[dependencies.ultrahardcoremod]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"